### ISSUE TITLE
Resolving a classpath url in java 11

### ISSUE THREAD

**Issue by perNyfelt** [perNyfelt/renjin#2]
on branch J11 beta1, the following issue occurs when doing `print(sessionInfo())`:

"classpath:///org/renjin/stats/Meta/package.rds".
org.renjin.eval.EvalException: Could not read file "classpath:///org/renjin/stats/Meta/package.rds".
	at org.renjin.primitives.R$primitive$gzfile.applyPromised(R$primitive$gzfile.java:46) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:46) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:58) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:42) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:43) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.eval.Context.evaluate(Context.java:283) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.DollarFunction.apply(DollarFunction.java:46) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:58) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:42) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:43) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.eval.Context.evaluate(Context.java:283) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.Evaluation.lapply(Evaluation.java:94) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$lapply.doApply(R$primitive$lapply.java:65) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$lapply.applyPromised(R$primitive$lapply.java:30) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:46) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:58) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:42) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Promise.doEval(Promise.java:87) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Promise.force(Promise.java:81) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.UseMethod.findObject(UseMethod.java:218) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.special.UseMethod.apply(UseMethod.java:99) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.Closure.apply(Closure.java:133) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.sexp.ExpressionVector.eval(ExpressionVector.java:85) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.eval.Context.evaluate(Context.java:283) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:174) ~[renjin-script-engine-3.5-dev.jar:?]
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:133) ~[renjin-script-engine-3.5-dev.jar:?]
	at se.alipsa.ride.console.ConsoleComponent.executeScriptAndReport(ConsoleComponent.java:930) ~[ride-1.2.7-SNAPSHOT.jar:?]
	at se.alipsa.ride.console.ConsoleComponent$3.call(ConsoleComponent.java:476) ~[ride-1.2.7-SNAPSHOT.jar:?]
	at se.alipsa.ride.console.ConsoleComponent$3.call(ConsoleComponent.java:471) ~[ride-1.2.7-SNAPSHOT.jar:?]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425) ~[javafx.graphics:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.commons.vfs2.FileSystemException: Could not read file "classpath:///org/renjin/stats/Meta/package.rds".
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1323) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:396) ~[commons-vfs2-2.0.jar:2.0]
	at org.renjin.primitives.io.connections.FileConnection.doOpenForInput(FileConnection.java:89) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.FileConnection.assureOpenForInput(FileConnection.java:78) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.FileConnection.open(FileConnection.java:60) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.Connections.newConnection(Connections.java:433) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.Connections.gzfile(Connections.java:77) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$gzfile.doApply(R$primitive$gzfile.java:70) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$gzfile.applyPromised(R$primitive$gzfile.java:35) ~[renjin-core-3.5-dev.jar:?]
	... 71 more
Caused by: java.lang.UnsupportedOperationException: TODO
	at org.renjin.eval.vfs.CompositeClassDirectoryObject.doGetInputStream(CompositeClassDirectoryObject.java:56) ~[renjin-core-3.5-dev.jar:?]
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1307) ~[commons-vfs2-2.0.jar:2.0]
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:396) ~[commons-vfs2-2.0.jar:2.0]
	at org.renjin.primitives.io.connections.FileConnection.doOpenForInput(FileConnection.java:89) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.FileConnection.assureOpenForInput(FileConnection.java:78) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.FileConnection.open(FileConnection.java:60) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.Connections.newConnection(Connections.java:433) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.io.connections.Connections.gzfile(Connections.java:77) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$gzfile.doApply(R$primitive$gzfile.java:70) ~[renjin-core-3.5-dev.jar:?]
	at org.renjin.primitives.R$primitive$gzfile.applyPromised(R$primitive$gzfile.java:35) ~[renjin-core-3.5-dev.jar:?]
	... 71 more

Possible solutions would be to either upgrade vfs2 or defer to something like classgraph

**Comment by perNyfelt** [comment]
Fixed in fixResolveFileClasspathUrl branch, commit ea013892ae1f6ab72968f71d94d7767ab55c3080
